import Head from 'next/head'
import { Inter } from 'next/font/google'
import BuyTitle from '@/components /Buy/BuyTitle'
import Pool from '@/components /Pool/Pool'
import Trade from '@/components /Buy/Trade'
import UserPosition from '@/components /User/UserPosition'
import UserStats from '@/components /User/UserStats'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SolCentralX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row pl-10 h-3/4 w-full pt-8 justify-between pr-5 justify-center'>
        <div className='flex flex-col w-3/5 h-full space-y-5 pl-5'>
          <div className='flex flex-col w-full bg-[#17182c] h-1/2 pl-5 pt-3 space-y-3'>
            <BuyTitle/>
            <div className='h-3/4 overflow-y-auto w-full flex flex-col space-y-3'>
              <Pool/>
              <Pool/>
              <Pool/>
              <Pool/>
              <Pool/>
              <Pool/>
            </div>
          </div>
          {/* <UserPosition/> */}
          <div className='flex flex-col w-full pt-3 space-y-3 h-3/5 pl-3 pr-3'>
              <UserStats/>
          </div>
        </div>
        <Trade/>
      </div>
    </>
  )
}
