import Head from 'next/head'
import { Inter } from 'next/font/google'
import BuyTitle from '@/components /Buy/BuyTitle'
import Pool from '@/components /Pool/Pool'
import Trade from '@/components /Buy/Trade'
import UserPosition from '@/components /User/UserPosition'
import UserStats from '@/components /User/UserStats'
import TradeMain from '@/components /Trade/TradeMain'
import { useEffect } from 'react'
import { useFetchData } from './hook'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data, fetchData} = useFetchData()
  useEffect(() => {
      async function fetchDatas() {
        const response = await fetchData();
        console.log(response)
      }
      fetchDatas();
  },[])

  return (
    <>
      <Head>
        <title>SolDecentral</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row pl-10 h-5/6 w-full pt-5 justify-between pr-5 justify-center'>
        <div className='flex flex-col w-2/3 h-full pl-5'>
          <div className='flex flex-col w-full bg-[#17182c] h-2/3 pl-5 pt-3 space-y-1 rounded'>
            chart
          </div>
          <TradeMain/>
        </div>
        <Trade/>
      </div>
    </>
  )
}
